//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public int PlantID { get; set; }
        public string PlantName { get; set; }
        public string PlantAddress { get; set; }
        public string PlantPhonenumber { get; set; }
        public int ResponsiblePersonID { get; set; }
        public int RegionID { get; set; }
    }
}
