//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica5
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceList
    {
        public int PriceID { get; set; }
        public int ProductID { get; set; }
        public int PlantID { get; set; }
        public int ResponsiblePersonID { get; set; }
        public double Price { get; set; }
        public string DateOfChange { get; set; }
    }
}
